spring.application.name=buspass

spring.datasource.url=jdbc:mysql://localhost:3306/buspass_db
spring.datasource.username=root
spring.datasource.password=Eagle92@sky#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080